# config/_default/menus.yaml

# Guide: https://docs.hugoblox.com/page-builder/#menus

main:
  - name: Curso
    url: ''
    weight: 20
  - name: Integração entre Tecnologia e Saúde
    url: 'curso/integracao/'
    parent: Curso
    weight: 1
  - name: Currículo 2023
    url: 'curso/curriculo-2023/'
    parent: Curso
    weight: 2
  - name: Projeto Pedagógico
    url: 'curso/projeto-pedagogico/'
    parent: Curso
    weight: 3

  # Mudamos de Grade&Docentes para apenas Docentes e removemos os "parents"
  - name: Docentes
    url: 'grade/docentes/'
    weight: 30

  # Nova aba de Oportunidades adicionada antes de Documentos
  - name: Oportunidades
    url: 'oportunidades/'
    weight: 35

  # - name: Grade&Docentes
  #   identifier: grade
  #   weight: 20
  # - name: Grade semestral
  #   parent: grade
  #   url: 'grade/grade-semestral/'
  #   weight: 1
  # - name: Docentes
  #   parent: grade
  #   url: 'grade/docentes/'
  #   weight: 2
  # - name: Grade 2023
  #   parent: grade
  #   url: 'grade/grade-2023/'
  #   weight: 4
  # - name: Projeto pedagogico
  #   parent: grade
  #   url: 'grade/projeto-pedagogico/'
  #   weight: 5

  - name: Documentos
    identifier: documentos
    weight: 30
  - name: Normas e Procedimentos
    parent: documentos
    url: 'documentos/normas-e-procedimentos'
    weight: 1
  - name: Formulários
    parent: documentos
    url: 'documentos/formularios'
    weight: 2
  - name: Tcc de Curso
    parent: documentos
    url: 'documentos/tcc-de-curso/'
    weight: 4

  - name: Estágios
    identifier: estagios
    weight: 40
  - name: Regras de Estágio
    parent: estagios
    url: /estagios/regras/
    weight: 1
  - name: Fluxo de Estágio
    parent: estagios
    url: /estagios/fluxo/
    weight: 2
  - name: Perguntas Frequentes
    parent: estagios
    url: /estagios/perguntas/
    weight: 3

  - name: Atividades Formativas
    identifier: atividades
    weight: 50
  - name: Formularios e Normas
    parent: atividades
    url: /atividades/formularios-e-normas/
    weight: 1
  - name: Passo a passo
    parent: atividades
    url: /atividades/passo-a-passo/
    weight: 2
  - name: Perguntas Frequentes
    parent: atividades
    url: /atividades/perguntas/
    weight: 3

  # - name: antigo
  #   identifier: antigo
  #   weight: 55
  # - name: Curriculo 2011
  #   parent: antigo
  #   url: /antigo/curriculo-2011/
  #   weight: 1
  # - name: grade 2011
  #   parent: antigo
  #   url: /antigo/grade-2011/
  #   weight: 2
  # - name: projeto pedagogico 2011
  #   parent: antigo
  #   url: /antigo/projeto-pedagogico-2011/
  #   weight: 3

  # - name: Noticias
  #   url: 'post/'
  #   weight: 60

  - name: Contato
    url: 'contact/'
    weight: 70
